version: "3"

services:
  fella:
    image: registry.local:5000/fella:latest
    environment:
      JAVA_ARGS: -Xmx256m -Xms256m
      DB_SERVER: 192.168.0.64
      AUTH_SERVER: http://auth-server:9000
    links:
      - fellaauth:auth-server
    expose:
      - 8090
    ports:
      - "8090:8090"

  fellaauth:
    image: registry.local:5000/fellaauth:latest
    environment:
      JAVA_ARGS: -Xmx256m -Xms256m
      ISSUER_URL: http://auth-server:9000
      REDIRECT_URI_1: http://fellaclient:8080/login/oauth2/code/messaging-client-oidc
      REDIRECT_URI_2: http://fellaclient:8080/authorized
    expose:
      - 9000
    ports:
      - "9000:9000"

  fellaclient:
    image: registry.local:5000/fellaclient:latest
    links:
      - fella:fellaapp
      - fellaauth:auth-server
    environment:
      JAVA_ARGS: -Xmx256m -Xms256m
      REDIRECT_URI_1: http://fellaclient:8080/login/oauth2/code/{registrationId}
      REDIRECT_URI_2: http://fellaclient:8080/authorized
      ISSUER_URI: http://auth-server:9000
      BASE_URI: http://fella:8090/messages
    expose:
      - 8085
    ports:
      - "8085:8080"
