-- CREATE TABLE IF NOT EXISTS field_types (
--                                id int GENERATED ALWAYS AS IDENTITY NOT NULL,
--                                type int NOT NULL UNIQUE,
--                                PRIMARY KEY (id)
-- );
--
-- CREATE TABLE IF NOT EXISTS field_type (
--                                 id varchar (255) NOT NULL,
--                                 name varchar (255) NOT NULL,
--                                 type int NOT NULL,
--                                 created_at timestamp NOT NULL DEFAULT NOW(),
--                                 PRIMARY KEY (id),
--                                 FOREIGN KEY (type)
--                                     REFERENCES field_types(type)
-- );
--
-- CREATE TABLE IF NOT EXISTS fields (
--                                id varchar (255) NOT NULL,
--                                monitorTypeId varchar (255) NOT NULL,
--                                fieldTypeId varchar (255) NOT NULL,
--                                created_at timestamp NOT NULL DEFAULT NOW(),
--                                PRIMARY KEY (id)
-- );
--
-- CREATE TABLE IF NOT EXISTS monitor_type (
--                           id varchar (255) NOT NULL,
--                           userId varchar (255) NOT NULL,
--                           name varchar (255) NOT NULL,
--                           created_at timestamp NOT NULL,
--                           PRIMARY KEY (id)
-- );
--
-- CREATE TABLE IF NOT EXISTS monitor (
--                                 id varchar (255)  NOT NULL,
--                                 userId varchar (255) NOT NULL,
--                                 name varchar (255) NOT NULL,
--                                 created_at timestamp NOT NULL DEFAULT NOW(),
--                                 PRIMARY KEY (id)
-- );
--
-- CREATE TABLE IF NOT EXISTS users (
--                         id varchar (255) NOT NULL,
--                         username varchar (255) NOT NULL,
--                         created_at timestamp NOT NULL DEFAULT NOW(),
--                         PRIMARY KEY (id)
-- );
--
-- INSERT INTO monitor (id, userId, name) VALUES (1, 1, 'period');
--
-- INSERT INTO field_types (type) VALUES (1);
-- INSERT INTO field_types (type) VALUES (2);
-- INSERT INTO field_types (type) VALUES (3);
-- INSERT INTO field_types (type) VALUES (4);
-- INSERT INTO field_types (type) VALUES (5);
--
-- INSERT INTO field_type (id, name, type) VALUES ('1', 'Date', 1);
-- INSERT INTO field_type (id, name, type) VALUES ('2', 'Pain Level', 2);
-- INSERT INTO field_type (id, name, type) VALUES ('3', 'Flow Level', 3);
-- INSERT INTO field_type (id, name, type) VALUES ('4', 'Notes', 4);
-- INSERT INTO field_type (id, name, type) VALUES ('5', 'Tags', 5);

-- CREATE TABLE IF NOT EXISTS tablets (
--     id varchar (255) NOT NULL,
--     userId varchar (255) NOT NULL,
--     created_at timestamp NOT NULL DEFAULT NOW(),
--     PRIMARY KEY (id)
--     FOREIGN KEY (userId),
--         REFERENCES users (id)
-- )
